### ISSUE TITLE
Only First Byte of A Pixel Is Read?

### ISSUE THREAD

**Issue by abhra0897** [ComputerNerd/ov7670-no-ram-arduino-uno#26]
`while(hg--){`
                `    lg2=wg;`
               `     while(lg2--){`
                        `        while((PIND&4));//wait for low`
                        `        UDR0=(PINC&15)|(PIND&240);`
                        `        while(!(PIND&4));//wait for high`
              `      }`
       ` }`

The above code in `static void captureImg(uint16_t wg,uint16_t hg)` function only reads a single Byte for a pixel in each clock cycle (PCLK). But, 1 pixel is made of 2 bytes, as per the OV7670 datasheet. Can you please explain it?

**Comment by natthalip** [comment]
Hi. I need help!!! @ComputerNerd 
What is variable of the value that we get from module camera (pixel).
I just want the value from camera to do something else.
Can you tell me please?
Thank you!

**Comment by abhra0897** [comment]
@natthalip to store a single row, before "UDR0=(PINC&15)|(PIND&240);",  add this line: uint8_t single_row = (PINC&15)|(PIND&240); and replace UDR0=(PINC&15)|(PIND&240); with UDR0 = single_row;

Note: uno doesn't have enough ram to store all the rows . So, you have to save every row in SD card (or a flash storage), or send them through UART.

**Comment by natthalip** [comment]
Thank you very much! @abhra0897
